window.noname_update={
	version:'1.9.58.1',
	update:'1.9.58',
	changeLog:[
		'bug修复'
	],
	files:[
		'character/hearth.js',
		'character/swd.js',
		'character/xianjian.js',
		'game/game.js',
		'mode/identity.js',
		'mode/guozhan.js'
	]
};